# Generated by Django 4.1.5 on 2023-02-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("username", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("addressline1", models.CharField(max_length=50)),
                ("addressline2", models.CharField(max_length=50)),
                ("pincode", models.CharField(max_length=15)),
                ("city", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=20)),
            ],
        ),
    ]
