# Generated by Django 4.1.5 on 2023-02-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0005_seller_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="pic",
            field=models.ImageField(
                blank=True, default="None", null=True, upload_to="images/"
            ),
        ),
    ]
