# Generated by Django 4.1.5 on 2023-03-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0006_alter_seller_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainApp.seller",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="pic1",
            field=models.ImageField(
                blank=True, default="None", null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="pic2",
            field=models.ImageField(
                blank=True, default="None", null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="pic3",
            field=models.ImageField(
                blank=True, default="None", null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="pic4",
            field=models.ImageField(
                blank=True, default="None", null=True, upload_to="images/"
            ),
        ),
    ]
