# Generated by Django 4.1.5 on 2023-03-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mainApp",
            "0007_product_seller_alter_product_pic1_alter_product_pic2_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                (
                    "addressline1",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "addressline2",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "addressline3",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "pin",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "pic",
                    models.ImageField(
                        blank=True, default="None", null=True, upload_to="images/"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="seller", name="email", field=models.EmailField(max_length=50),
        ),
    ]
