# Generated by Django 4.1.5 on 2023-04-04 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0009_wishlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckOut",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product", models.CharField(max_length=10)),
                ("shipping", models.IntegerField()),
                ("finalamount", models.IntegerField()),
                ("total", models.IntegerField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Not Packed yet"),
                            (2, "Items Packed"),
                            (3, "Out for Delivery"),
                            (4, "Delivered"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "paymentstatus",
                    models.IntegerField(
                        choices=[(1, "Pending"), (2, "Done")], default=1
                    ),
                ),
                (
                    "mode",
                    models.IntegerField(
                        choices=[(1, "COD"), (2, "Online Payment")], default=1
                    ),
                ),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "orderid",
                    models.CharField(
                        blank=True, default=True, max_length=50, null=True
                    ),
                ),
                (
                    "paymentid",
                    models.CharField(
                        blank=True, default=True, max_length=50, null=True
                    ),
                ),
                (
                    "paymentsignature",
                    models.CharField(
                        blank=True, default=True, max_length=50, null=True
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainApp.buyer"
                    ),
                ),
            ],
        ),
    ]
