# Generated by Django 4.1.5 on 2023-04-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0010_checkout"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="mode",
            field=models.IntegerField(
                choices=[(1, "Cash on Delivery"), (2, "Online Payment")], default=1
            ),
        ),
    ]
