# Generated by Django 4.1.5 on 2023-04-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0013_contactus"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer", name="otp", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="seller", name="otp", field=models.IntegerField(default=0),
        ),
    ]
